name: hotel_task
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  intl: ^0.18.1
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  flutter_easyloading: ^3.0.5
  dartz: ^0.10.1
  easy_localization: ^3.0.0
  chopper: ^6.1.4
  built_value: ^8.8.1
  built_collection: ^5.1.1
  logger: ^2.0.2+1
  # google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  progress_indicators: ^1.0.0
  cached_network_image: ^3.3.1
  # intl_phone_number_field: ^0.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.4
  chopper_generator: ^6.0.3
  built_value_generator: ^8.1.2

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/
    - assets/translation/
    - assets/images/
    - assets/icons/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/sf_pro_display/sf-pro-text-bold.ttf
          weight: 700
        - asset: assets/fonts/sf_pro_display/sf-pro-text-semibold.ttf
          weight: 600
        - asset: assets/fonts/sf_pro_display/sf-pro-text-medium.ttf
          weight: 500
        - asset: assets/fonts/sf_pro_display/sf-pro-text-regular.ttf
          weight: 400
    # - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
